openapi: 3.0.0
info:
  title: Repair Service
  description: A simple service to manage repairs
  version: 1.0.0
paths:
  /repair:
    get:
      operationId: repair
      summary: Returns a repair
      description: Returns a repair with its details and image     
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The unique identifier of the repair
                  title:
                    type: string
                    description: The short summary of the repair
                  description:
                    type: string
                    description: The detailed description of the repair
                  assignedTo:
                    type: string
                    description: The user who is responsible for the repair
                  date:
                    type: string
                    format: date-time
                    description: The date and time when the repair is scheduled or completed
                  image:
                    type: string
                    format: uri
                    description: The URL of the image of the item to be repaired or the repair process