name: Teams JS SDK New Version Released
on:
  repository_dispatch:
    types: [teamsjs-released]
jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install npm packages
        run: |
          npm install node-fetch-commonjs
          npm install markdown-it

      - name: Get Release Detail
        id: detail
        uses: actions/github-script@v6
        with:
          script: |
            var fetch = require('node-fetch-commonjs');
            var md = require('markdown-it')();
            const md_to_html = async() => {
                const response = await fetch('https://api.github.com/repos/OfficeDev/microsoft-teams-library-js/releases/tags/v'+'${{ github.event.client_payload.version }}');
                const data = await response.json();
                const note = await data.body;
                const url = await data.html_url;
                console.log(note);
                console.log("\nDetails can be found here: " + url);
                const emailBody = note + "\n\nDetails can be found here: " + url;
                emailBody_html = md.render(emailBody);
                return emailBody_html;
            }
            return md_to_html();

      - name: Setup Email and Recipient
        id: email
        run: |
          emails="vsciotadt@microsoft.com;zhididr@microsoft.com;johmil@microsoft.com"
          subject="Teams JS SDK v${{ github.event.client_payload.version }} Released"

          echo "to=$emails" >> $GITHUB_OUTPUT
          echo "subject=$subject" >> $GITHUB_OUTPUT